---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Add Kubernetes apt key.
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  register: add_repository_key
  ignore_errors: "{{ kubernetes_apt_ignore_key_error }}"

- name: Add Kubernetes repository.
  apt_repository:
    repo: "{{ kubernetes_apt_repository }}"
    state: present
    update_cache: true

- name: Add Kubernetes apt preferences file to pin a version.
  template:
    src: apt-preferences-kubernetes.j2
    dest: /etc/apt/preferences.d/kubernetes

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Create config file for br_netfilter module
  file:
    path: /etc/modules-load.d/k8s.config
    state: touch
    owner: root
    group: root
    mode: 0644

- name: Write config file for br_netfilter module
  lineinfile:
    path: /etc/modules-load.d/k8s.config
    line: br_netfilter

- name: Load br_netfilter module
  command: modprobe br_netfilter

- name: Enable net.ipv4.ip_forward in sysctl
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
  become: true

- name: Enable net.bridge.bridge-nf-call-ip6tables in sysctl
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
    state: present

- name: Enable net.bridge.bridge-nf-call-iptables in sysctl
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present

- name: "Reload sysctl"
  command: sysctl --system
